[package]
name = "dragonglass_app"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0.43"
dragonglass_render = { path = "../dragonglass_render" }
dragonglass_world = { path = "../dragonglass_world" }
image = "0.23.14"
imgui = "0.7.0"
imgui-winit-support = "0.7.1"
log = "0.4.14"
nalgebra-glm = "0.15.0"
pollster = "0.2.4"
serde = { version = "1.0.127", features = ["derive"] }
simplelog = { version = "0.10.0", features = ["termcolor"] }
winit = "0.25.0"
