[package]
name = "dragonglass_app"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0.34"
dragonglass_physics = { path = "../dragonglass_physics" }
dragonglass_render = { path = "../dragonglass_render" }
dragonglass_world = { path = "../dragonglass_world" }
image = "0.23.12"
imgui = "0.6.1"
imgui-winit-support = "0.6.0"
log = "0.4.11"
nalgebra-glm = "0.9.0"
ncollide3d = "0.26.1"
serde = { version = "1.0.117", features = ["derive"] }
simplelog = { version = "0.9.0", features = ["termcolor"] }
winit = "0.24.0"
