[package]
name = "editor"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"
default-run = "editor"

[dependencies]
anyhow = "1.0.40"
dragonglass = { path = "../.." }
log = "0.4.14"
nalgebra = "0.25.3"
nalgebra-glm = "0.11.0"
imgui = "0.7.0"
winit = "0.24.0"
hotwatch = "0.4.5"
structopt = "0.3.21"
