[package]
name = "editor"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"
default-run = "editor"

[dependencies]
anyhow = "1.0.44"
dragonglass = { path = "../.." }
log = "0.4.14"
nalgebra = "0.29.0"
nalgebra-glm = "0.15.0"
winit = { version = "0.25.0", features=["web-sys"] }
structopt = "0.3.23"
