[package]
name = "dragonglass_physics"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
nalgebra-glm = "0.9.0"
rapier3d = { version = "0.4.2", features = ["serde-serialize"] }
serde = { version = "1.0.118", features = ["derive"] }