[package]
name = "dragonglass"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[workspace]
exclude = ["benches"]
members = ["crates/*"]

[dependencies]
dragonglass_app = { path = "crates/dragonglass_app" }
dragonglass_physics = { path = "crates/dragonglass_physics" }
dragonglass_render = { path = "crates/dragonglass_render" }
dragonglass_world = { path = "crates/dragonglass_world" }

[dev-dependencies]
anyhow = "1.0.36"
log = "0.4.11"
imgui = "0.6.1"
winit = "0.24.0"
