[package]
name = "dragonglass"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[workspace]
exclude = ["benches"]
members = ["crates/*", "apps/*"]
default-members = ["apps/*"]

[dependencies]
dragonglass_app = { path = "crates/dragonglass_app" }
dragonglass_render = { path = "crates/dragonglass_render" }
dragonglass_world = { path = "crates/dragonglass_world" }
