[package]
name = "dragonglass"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[workspace]
exclude = ["benches"]
members = ["crates/*", "editor", "game"]
default-members = ["editor", "game"]

[dependencies]
dragonglass_app = { path = "crates/dragonglass_app" }
dragonglass_physics = { path = "crates/dragonglass_physics" }
dragonglass_render = { path = "crates/dragonglass_render" }
dragonglass_world = { path = "crates/dragonglass_world" }
