[package]
name = "game"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
dragonglass = { path = "../.." }
imgui = "0.7.0"
log = "0.4.14"
nalgebra = "0.26.1"
nalgebra-glm = "0.12.0"
pollster = "0.2.4"
rapier3d = "0.8.0"
winit = "0.24.0"