[package]
name = "dragonglass_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.15.0"
egui_wgpu_backend = "0.14.0"
egui_winit_platform = "0.11.0"
epi = "0.15.0"
wgpu = { version = "0.11.0", features=["webgl"] }
winit = {version = "0.25.0", features=["web-sys"]}