[package]
name = "dragonglass_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
egui = "0.16.0"
egui_wgpu_backend = "0.15.0"
egui_winit_platform = "0.12.0"
epi = "0.16.0"
wgpu = { version = "0.12.0", features = ["webgl"] }
winit = "0.26.0"
