[package]
edition = "2021"
name = "dragonglass_gui"
version = "0.1.0"

[dependencies]
egui = "0.16.1"
egui-gizmo = "0.5.0"
egui_winit_platform = "0.13.0"
epi = "0.16.0"
nalgebra-glm = {version = "0.16.0", features = ["serde-serialize"]}
winit = "0.26.1"
