[package]
name = "dragonglass_opengl"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
gl = "0.14.0"
glutin = "0.26.0"
image = "0.23.14"
log = "0.4.14"
nalgebra-glm = "0.12.0"
raw-window-handle = "0.3.3"