[package]
name = "dragonglass_world"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
gltf = { version = "0.15.2", features = ["names", "KHR_lights_punctual", "KHR_materials_unlit"] }
hecs = { git = "https://github.com/Ralith/hecs", features = ["serde"] }
image = "0.23.14"
log = "0.4.14"
nalgebra = "0.25.3"
nalgebra-glm = { version = "0.11.0", features = ["serde-serialize"] }
petgraph = { version = "0.5.1", features = ["serde-1"] }
serde = { version = "1.0.125", features = ["derive"] }
