[package]
name = "dragonglass_world"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0.34"
dragonglass_physics = { path = "../dragonglass_physics" }
gltf = { version = "0.15.2", features = ["names", "KHR_lights_punctual", "KHR_materials_unlit"] }
hecs = "0.3.1"
image = "0.23.12"
log = "0.4.11"
nalgebra-glm = { version = "0.9.0", features = ["serde-serialize"] }
petgraph = { version = "0.5.1", features = ["serde-1"] }
serde = { version = "1.0.117", features = ["derive"] }
