[package]
name = "viewer"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
log = "0.4.11"
simplelog = { version = "0.8.0", features = ["termcolor"] }
winit = "0.22.2"