[package]
name = "dragonglass_render"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
derive_builder = "0.9.0"
dragonglass_physics = { path = "../dragonglass_physics" }
dragonglass_world = { path = "../dragonglass_world" }
dragonglass_vulkan = { path = "../dragonglass_vulkan" }
log = "0.4.14"
image = "0.23.14"
imgui = "0.7.0"
nalgebra-glm = "0.11.0"
ncollide3d = "0.28.0"
hecs = { git = "https://github.com/Ralith/hecs", features = ["serde"] }
petgraph = "0.5.1"
rapier3d = "0.6.1"
raw-window-handle = "0.3.3"
shader-compilation = { path = "../shader-compilation" }

[build-dependencies]
log = "0.4.14"
shader-compilation = { path = "../shader-compilation" }
simplelog = { version = "0.10.0", features = ["termcolor"] }
