[package]
name = "dragonglass_render"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0.52"
bytemuck = { version = "1.7.3", features = ["derive"] }
derive_builder = "0.10.2"
dragonglass_gui = { path = "../dragonglass_gui" }
dragonglass_world = { path = "../dragonglass_world" }
getrandom = { version = "0.2.3", features = ["js"] }
image = "0.23.14"
log = "0.4.14"
nalgebra-glm = "0.15.0"
petgraph = "0.6.0"
rapier3d = { version = "0.11.1", features = ["serde-serialize", "wasm-bindgen"] }
raw-window-handle = "0.4.2"
winit = "0.26.0"
wgpu = { version = "0.12.0", features = ["webgl"] }
