[package]
name = "dragonglass_render"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
derive_builder = "0.10.0"
dragonglass_world = { path = "../dragonglass_world" }
log = "0.4.14"
image = "0.23.14"
nalgebra-glm = "0.12.0"
petgraph = "0.5.1"
rapier3d = "0.8.0"
raw-window-handle = "0.3.3"
shader-compilation = { path = "../shader-compilation" }

dragonglass_opengl = { path = "../dragonglass_opengl", optional = true }
dragonglass_vulkan = { path = "../dragonglass_vulkan", optional = true }

[build-dependencies]
log = "0.4.14"
shader-compilation = { path = "../shader-compilation" }
simplelog = { version = "0.10.0", features = ["termcolor"] }

[features]
default = ["opengl", "vulkan"]
opengl = ["dragonglass_opengl"]
vulkan = ["dragonglass_vulkan"]
