[package]
name = "dragonglass_render"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0.44"
bytemuck = { version = "1.7.2", features = ["derive"] }
derive_builder = "0.10.2"
dragonglass_world = { path = "../dragonglass_world" }
image = "0.23.14"
log = "0.4.14"
nalgebra-glm = "0.15.0"
petgraph = "0.6.0"
rapier3d = { version = "0.11.1", features = ["serde-serialize", "wasm-bindgen"] }
raw-window-handle = "0.3.3"
wgpu = { version = "0.11.0", features=["webgl"] }
getrandom = { version = "0.2", features = ["js"] }
