name: Rust CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get install -y libcairo2-dev libjpeg-dev libgif-dev
      - uses: actions/checkout@v1
      - uses: icepuma/rust-action@master
        with:
          args: cargo fmt -- --check && cargo clippy && cargo test
